const jobs = [
  {
    id: "job-001",
    title: "养老院护工",
    salary: "160元/天",
    location: "南京鼓楼区",
    distance: "离你约 2.1 公里",
    workTime: "8:00-18:00，每周一至周五",
    category: "护工",
    ageRequirement: "45-62岁",
    headcount: 2,
    benefits: ["包午饭", "有人带", "可日结"],
    description: "协助老人吃饭、散步、整理房间，工作内容稳定。",
    requirement: "身体健康，有耐心；有照护经验更好，没有经验也可以先培训。",
    employerName: "安心养老院",
    employerContact: "李老师",
    contactPhone: "13800008888",
    wechatId: "zhaolinggong001",
    status: "open",
    urgent: true
  },
  {
    id: "job-002",
    title: "小区门卫",
    salary: "120元/天",
    location: "南京玄武区",
    distance: "离你约 4.8 公里",
    workTime: "9:00-17:00，可排班",
    category: "门卫",
    ageRequirement: "50-68岁",
    headcount: 1,
    benefits: ["活轻松", "坐班", "不限经验"],
    description: "负责门口登记、简单指引和巡看，工作强度低。",
    requirement: "会使用手机接电话，普通话沟通清楚，责任心强。",
    employerName: "阳光社区物业",
    employerContact: "王主管",
    contactPhone: "13900006666",
    wechatId: "sunnywuye",
    status: "open",
    urgent: false
  },
  {
    id: "job-003",
    title: "食堂帮工",
    salary: "150元/天",
    location: "南京秦淮区",
    distance: "离你约 3.5 公里",
    workTime: "6:30-13:30，做六休一",
    category: "食堂",
    ageRequirement: "45-60岁",
    headcount: 3,
    benefits: ["包早午饭", "固定白班", "上手快"],
    description: "帮忙洗菜、分餐、收拾餐盘，不需要炒菜。",
    requirement: "身体健康，手脚麻利，能早起。",
    employerName: "城东社区食堂",
    employerContact: "赵店长",
    contactPhone: "13700009999",
    wechatId: "cdshitang",
    status: "open",
    urgent: true
  },
  {
    id: "job-004",
    title: "超市理货员",
    salary: "140元/天",
    location: "南京建邺区",
    distance: "离你约 5.2 公里",
    workTime: "8:30-16:30，可做半天",
    category: "理货",
    ageRequirement: "45-60岁",
    headcount: 2,
    benefits: ["不用搬重物", "可半天", "有人带"],
    description: "整理货架、补充商品、贴价签，工作环境在室内。",
    requirement: "认识常用商品，能长时间站立，做事细心。",
    employerName: "惠民生活超市",
    employerContact: "刘店长",
    contactPhone: "13611112222",
    wechatId: "huiminmarket",
    status: "open",
    urgent: false
  },
  {
    id: "job-005",
    title: "医院陪诊员",
    salary: "180元/次",
    location: "南京鼓楼区",
    distance: "离你约 6.0 公里",
    workTime: "按次安排，上午较多",
    category: "陪诊",
    ageRequirement: "45-58岁",
    headcount: 4,
    benefits: ["时间灵活", "会培训", "收入高"],
    description: "陪老人挂号、取号、排队、取药，必要时帮忙联系家属。",
    requirement: "熟悉手机导航和医院流程，有耐心，沟通清楚。",
    employerName: "暖心陪诊服务站",
    employerContact: "陈老师",
    contactPhone: "13522223333",
    wechatId: "nuanxinpeizhen",
    status: "open",
    urgent: true
  },
  {
    id: "job-006",
    title: "小区保洁",
    salary: "130元/天",
    location: "南京栖霞区",
    distance: "离你约 1.4 公里",
    workTime: "7:00-12:00，上午半天",
    category: "保洁",
    ageRequirement: "50-65岁",
    headcount: 2,
    benefits: ["离家近", "半天班", "活稳定"],
    description: "负责楼道、电梯间和院内公共区域清扫。",
    requirement: "身体健康，能按时到岗，做事认真。",
    employerName: "安居物业",
    employerContact: "孙主管",
    contactPhone: "13433334444",
    wechatId: "anjuwuye",
    status: "open",
    urgent: false
  },
  {
    id: "job-007",
    title: "社区快递分拣",
    salary: "100元/半天",
    location: "南京江宁区",
    distance: "离你约 7.8 公里",
    workTime: "14:00-18:00，下午半天",
    category: "分拣",
    ageRequirement: "45-62岁",
    headcount: 3,
    benefits: ["日结", "半天班", "上手快"],
    description: "按小区楼号整理快递，协助居民取件。",
    requirement: "能看清地址，能搬动小件包裹，不搬大件。",
    employerName: "邻里驿站",
    employerContact: "周站长",
    contactPhone: "13344445555",
    wechatId: "linliyizhan",
    status: "open",
    urgent: true
  },
  {
    id: "job-008",
    title: "家政钟点工",
    salary: "45元/小时",
    location: "南京雨花台区",
    distance: "离你约 4.1 公里",
    workTime: "每周二、四上午",
    category: "家政",
    ageRequirement: "45-60岁",
    headcount: 1,
    benefits: ["按小时", "离家近", "长期稳定"],
    description: "家庭日常清洁，厨房、客厅、卫生间简单打扫。",
    requirement: "有家政或保洁经验，讲卫生，守时。",
    employerName: "个人雇主",
    employerContact: "张女士",
    contactPhone: "13255556666",
    wechatId: "zhanghome888",
    status: "open",
    urgent: false
  }
];

const worker = {
  name: "王叔叔",
  gender: "男",
  age: 62,
  phone: "13600001234",
  maskedPhone: "136****1234",
  city: "南京",
  district: "鼓楼区",
  realName: "王建国",
  idCardMasked: "3201**********3218",
  realNameStatus: "已实名认证",
  healthStatus: "身体健康",
  emergencyContact: "王女士 138****6688",
  expectedJobs: "门卫、护工、食堂帮工",
  availableTime: "白天有空",
  workExperience: "做过小区门卫两年，也能做简单保洁",
  contactProtection: "双方同意后才展示联系方式"
};

const mockApplications = [
  {
    id: "apply-demo-001",
    jobId: "job-002",
    jobTitle: "小区门卫",
    salary: "120元/天",
    location: "南京玄武区",
    workerName: "王叔叔",
    workerPhone: "13600001234",
    employerName: "阳光社区物业",
    employerContact: "王主管",
    employerPhone: "13900006666",
    wechatId: "sunnywuye",
    dailyInsurance: "provided",
    workerAgreed: true,
    employerAgreed: true,
    status: "matched",
    createdAt: "今天 09:20"
  },
  {
    id: "apply-demo-002",
    jobId: "job-006",
    jobTitle: "小区保洁",
    salary: "130元/天",
    location: "南京栖霞区",
    workerName: "王叔叔",
    workerPhone: "13600001234",
    employerName: "安居物业",
    employerContact: "孙主管",
    employerPhone: "13433334444",
    wechatId: "anjuwuye",
    dailyInsurance: "pending",
    workerAgreed: true,
    employerAgreed: false,
    status: "waiting",
    createdAt: "昨天 16:40"
  },
  {
    id: "apply-demo-003",
    jobId: "job-003",
    jobTitle: "食堂帮工",
    salary: "150元/天",
    location: "南京秦淮区",
    workerName: "王叔叔",
    workerPhone: "13600001234",
    employerName: "城东社区食堂",
    employerContact: "赵店长",
    employerPhone: "13700009999",
    wechatId: "cdshitang",
    dailyInsurance: "notProvided",
    workerAgreed: false,
    employerAgreed: true,
    status: "waiting",
    createdAt: "5月30日"
  }
];

module.exports = {
  jobs,
  worker,
  mockApplications
};
